# Done to increase the memory available to gradle.
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Fabric Properties
# check these on https://fabricmc.net/develop
minecraft_version=1.19.4
yarn_mappings=1.19.4+build.2
loader_version=0.15.11

# Fabric API
fabric_version=0.87.2+1.19.4

# Mod Properties
mod_version = 1.6.3
maven_group = com.hyfata
archives_base_name = koreanpatch-fabric
support_version = 1.19.4

# dependencies
modmenu_version = 6.3.1
command_block_ide_version = 0.4.2
better_command_block_ui_version = Fd2fux9v